# Generated by Django 3.2.3 on 2021-06-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='TopicPrro',
        ),
    ]
